#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# polybar
killall -q polybar
polybar -q &

# feh
feh --bg-fill ~/.wallpapers/tokyo.png

# picom
killall -q picom
picom &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           10
bspc config border_radius	       15

bspc config normal_border_color \#c0caf5
bspc config active_border_color \#c0caf5
bspc config focused_border_color \#c0caf5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Goldendict state=floating
bspc rule -a Rofi state=floating
bspc rule -a Nautilus state=floating
# fish
# set -U SXHKD_SHELL /user/bin/bash


# Java
wmname LG3D
