#! /bin/sh

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
# eww
# eww daemon &
# polybar
polybar &
# feh
feh --bg-fill --randomize --no-fehbg ~/Pictures/wallpaper/*
# picom
picom &
# redshift
redshift &

bspc monitor -d I II III IV V 
bspc monitor eDP-1-1 -d I II III IV V 
bspc monitor HDMI-0 -d I II III IV V 

# xrandr -q
# xrandr --output eDP-1-1 --auto --output HDMI-0 --auto --right-of eDP-1-1


bspc config border_width         0
bspc config window_gap           10
bspc config border_radius	       15

bspc config normal_border_color   \#c0caf5
bspc config active_border_color   \#c0caf5
bspc config focused_border_color  \#c0caf5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a goldendict state=floating
bspc rule -a Nautilus state=floating
bspc rule -a Rofi state=floating


# fish
# set -U SXHKD_SHELL /user/bin/bash


# Java
wmname LG3D
