#! /bin/sh

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
# eww
# eww daemon &
# polybar
polybar &
# feh
feh --bg-fill --randomize --no-fehbg ~/Pictures/wallpaper/*
# picom
picom &
# redshift
# redshift &
# dunst
dunst &
# touchpad
libinput-gestures-setup start  

copyq --start-server

bspc monitor -d I II III IV V 
bspc monitor eDP-1-1 -d I II III IV V 
bspc monitor HDMI-0 -d I II III IV V 

# xrandr -q
# xrandr --output eDP-1-1 --auto --output HDMI-0 --auto --right-of eDP-1-1

bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap           5

bspc config normal_border_color "#1e1e1e"
bspc config active_border_color  "#0245a3"
bspc config focused_border_color "#ac73ff"
bspc config presel_border_color "#ffffff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a copyq state=floating
bspc rule -a Nautilus state=floating
bspc rule -a Rofi state=floating


# fish
# set -U SXHKD_SHELL /user/bin/bash


# Java
wmname LG3D

